### ISSUE TITLE
Adapter for express js middleware

### ISSUE THREAD

**Issue by srghma** [Woody88/purescript-warp#5]
For example hyper has `mkMiddlewareFromForeign` method

https://github.com/purescript-hyper/hyper/issues/47#issuecomment-615226026

Is the same possible with warp?

**Comment by Woody88** [comment]
Hi @srghma, 

Yes, it's actually a great idea! warp is built as a handler for [wai](https://github.com/Woody88/purescript-wai), so as long as you can get the express middleware to match the `Application` type. It should be possible. So, we could make a `wai-express-js` middleware. Have a look at this https://github.com/Woody88/purescript-wai-websockets. 

I will try to look more into it later on.

**Comment by Woody88** [comment]
@srghma Sorry it took me a bit of time to get on this issue. I was focusing more on my other library ([purescript-swerve](https://github.com/Woody88/purescript-swerve/tree/swerve-server)). So, I implemented a solution that can allow you to add express middleware using `purescript-vault`.  

Here is a working example using express static. 

#### Main.js
```javascript
const serveStatic = require('serve-static')

exports._serveStatic = serveStatic('public')
```

#### Main.purs
```purescript
import Prelude

import Data.Maybe (Maybe(..))
import Data.Tuple.Nested ((/\))
import Data.Vault as V
import Effect (Effect)
import Effect.Class.Console as Console
import Network.HTTP.Types (ok200)
import Network.HTTP.Types.Header (hContentType)
import Network.Wai (Application, Middleware, responseStr)
import Network.Warp.FFI.Server (ForeignApplication, HttpHandles, httpHandlesKey, mkMiddlewareFromForeign)
import Network.Warp.Run (runSettings)
import Network.Warp.Settings (defaultSettings)
 
main :: Effect Unit
main = do 
  let beforeMainLoop = Console.log $ "Listening on port " <> show defaultSettings.port
  httpKey' <- httpHandlesKey  -- creates key that will allow the middleware to access node HTTP request and response object
  void $ runSettings defaultSettings { beforeMainLoop = beforeMainLoop, httpKey = Just httpKey' } 
       $ serverStatic httpKey' 
       $ app 

app :: Application 
app req f = do
    f $ responseStr ok200 [(hContentType /\ "text/plain")] "Hello World!"

serverStatic :: V.Key HttpHandles -> Middleware 
serverStatic k = mkMiddlewareFromForeign k _serveStatic

foreign import _serveStatic :: ForeignApplication
```

Let me know if you need more details. I will be working on polishing `warp`'s codebase and docs soon.

**Comment by robertdp** [comment]
My PR simplified this even further, and `httpKey` creation and setting is no longer required.
```purescript
mkMiddlewareFromForeign :: ForeignMiddleware -> Middleware
```

The `serveStatic` example becomes:
```purescript
main :: Effect Unit
main =
  void
    $ runSettings defaultSettings
    $ serverStatic
    $ app

app :: Application 
app _ send = send $ responseStr ok200 [(hContentType /\ "text/plain")] "Hello World!"

foreign import _serveStatic :: ForeignMiddleware

serveStatic :: Middleware 
serveStatic = mkMiddlewareFromForeign _serveStatic
```
